### ISSUE TITLE
Can't access admin panel

### ISSUE THREAD

**Issue by stlouisweb** [yogiben/meteor-admin#184]
I get the following error when trying to add an admin user / access the admin route:
 
"Exception while invoking method 'adminCheckAdmin' Error: When the modifier option is true, validation object must have at least one operator"

**Comment by bogdanrn** [comment]
i had the same issue and i fixed it by manually edditing my user account in the databas to add the role {$set: { roles : ["admin"] } } . It seems that if the user collection doesn't have the roles : [ ] it throws this error

**Comment by an0nym0use** [comment]
#163 Should solve this.

**Comment by mmintel** [comment]
I think #163 didn't solve it, because I am having the same issue.

**Comment by bogdanrn** [comment]
I had the same issue again, maybe my initial fix worked for my isolated problem only. I found another one in my code when i removed the 'insecure' package. 
The user document when you publish it to the client needs to have the "roles" field too. 

return Meteor.users.find({}, {'emails': true, 'profile':true, 'roles':true});

Also if you attach a profile schema like i did, for me it worked with this configuration: 
Schemas.User = new SimpleSchema({
  ................
	roles: {
		type: Object,
		blackbox:true,
		optional: true
	},
  .............
});

**Comment by almogdesign** [comment]
I'm having the same issue was anyone able to solve it?

**Comment by bogdanrn** [comment]
i'm pretty sure it was fixed by now. Have you tried the solutions posted above? What does your error log say ?

**Comment by almogdesign** [comment]
I think I know what's casing this, I'm using the roles package for custom roles in my app 

I'm getting the following error 

 Exception while invoking method 'adminCheckAdmin' TypeError: Cannot read property 'length' of undefined
I20151012-00:49:35.399(3)?     at [object Object].Meteor.methods.adminCheckAdmin (packages/yogiben_admin/lib/server/methods.coffee:78:82)
I20151012-00:49:35.399(3)?     at packages/check/packages/check.js:117:1
I20151012-00:49:35.399(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151012-00:49:35.399(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/packages/check.js:116:1)
I20151012-00:49:35.399(3)?     at maybeAuditArgumentChecks (livedata_server.js:1689:18)
I20151012-00:49:35.400(3)?     at livedata_server.js:708:19
I20151012-00:49:35.400(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151012-00:49:35.400(3)?     at livedata_server.js:706:40
I20151012-00:49:35.400(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151012-00:49:35.400(3)?     at livedata_server.js:704:46
I20151012-00:49:35.400(3)?     at tryCallTwo (/Users/Almog/.meteor/packages/promise/.0.5.0.1ivq8ra++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151012-00:49:35.400(3)?     at doResolve (/Users/Almog/.meteor/packages/promise/.0.5.0.1ivq8ra++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151012-00:49:35.400(3)?     at new Promise (/Users/Almog/.meteor/packages/promise/.0.5.0.1ivq8ra++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151012-00:49:35.400(3)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20151012-00:49:35.400(3)?     at livedata_server.js:548:43

**Comment by bogdanrn** [comment]
it looks like the same problem, try all the steps in the comments above, it fixed it for me. If you don't understand something just say and as a future notice for you: next time when you post about a problem, try to offer as much info as possible (what error you have, what you tried, etc.), this way maybe someone recognizes something and you have higher chances of getting a reply. 
-Are you running the latest versions of the packages ? 
-Are you using database schemas ? If so, have you added the `roles` part to it? 
-Did you add the roles after the admin user was created? Can you try delete the admin from mongo and recreate a new one? 

My problem was caused by the fact the the admin record i had in the database didn't had any `role` attached to it. Check that first.

**Comment by almogdesign** [comment]
I tried the above options it did not help why I added my comment

**Comment by almogdesign** [comment]
I was able to fix it by adding admin, but the core issue is you can't set your own custom role

**Comment by bogdanrn** [comment]
what do you mean ?

**Comment by almogdesign** [comment]
I have different roles setup in my app 
'user','site-administrator', 'system-administrator',

As I'm using the roles package inside my app, but with meteor admin you can't do this. Meteor admin should scope the admin role or let me set different admin roles like  'system-administrator' 

I also tried the email option but that did not work

**Comment by django43ru** [comment]
Thanks, @bogdanrn! This helped me:

Schemas.User = new SimpleSchema({
  ................
    roles: {
        type: Object,
        blackbox:true,
        optional: true
    },
  .............
});
