### ISSUE TITLE
a plugin for *.less was active when it was published but none

### ISSUE THREAD

**Issue by mapitPhonegap** [yogiben/meteor-admin#366]
Hi,

I have this error, please advice:

Errors prevented startup:

   While building for web.browser:
   error: no plugin found for lib/client/css/admin-custom.less in yogiben:admin; a plugin for *.less was active when it was published but none
   is now

**Comment by jc2** [comment]
Same error here but i fixed it doing the following:
- meteor remove yogiben:admin
- meteor add less
- meteor add yogiben:admin

**Comment by mapitPhonegap** [comment]
Still the same =(...I think I just forget about it, thanks anyway

**Comment by felixb101** [comment]
Same issue

**Comment by LeonidShamis** [comment]
+1 - Same issue

Tried the steps suggested by @jc2 above, but it didn't help:

> meteor

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building for web.browser:
   error: no plugin found for lib/client/css/admin-custom.less in yogiben:admin; a plugin for *.less was active when it was published but none is now

=> Your application has errors. Waiting for file change.
Terminate batch job (Y/N)? y

> meteor remove yogiben:admin

Changes to your project's package version selections:

aldeed:tabular             removed from your project
aldeed:template-extension  removed from your project
meteorhacks:meteorx        removed from your project
meteorhacks:unblock        removed from your project
mfactory:admin-lte         removed from your project
raix:handlebar-helpers     removed from your project
twbs:bootstrap             removed from your project
yogiben:admin              removed from your project
zimme:active-route         removed from your project

yogiben:admin: removed dependency

> meteor add less
> less without a version constraint has already been added.
> 
> find "less" .meteor\versions
> ---------- .METEOR\VERSIONS
> less@1.0.14
> 
> meteor add yogiben:admin

Changes to your project's package version selections:

aldeed:tabular             added, version 1.4.2
aldeed:template-extension  added, version 4.0.0
meteorhacks:meteorx        added, version 1.4.1
meteorhacks:unblock        added, version 1.1.0
mfactory:admin-lte         added, version 0.0.2
raix:handlebar-helpers     added, version 0.2.5
twbs:bootstrap             added, version 3.3.6
yogiben:admin              added, version 1.2.8
zimme:active-route         added, version 2.3.2

yogiben:admin: A complete admin dashboard solution

> meteor
> [[[[[  ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building for web.browser:
   error: no plugin found for lib/client/css/admin-custom.less in yogiben:admin; a plugin for *.less was active when it was published but none is now

=> Your application has errors. Waiting for file change.

**Comment by jc2** [comment]
have you tried a meteor reset after remove yogiben:admin?

**Comment by LeonidShamis** [comment]
I just tried and it didn't help:

```
meteor remove yogiben:admin
meteor reset
meteor update less
meteor add yogiben:admin

```

See the results (including versions info - meteor --version && node -v && npm -v) below:

meteor-admin-lte > meteor
[[[[[ meteor-admin-lte ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building for web.browser:
   error: no plugin found for lib/client/css/admin-custom.less in yogiben:admin; a plugin for *.less was active when it was published but none is now

=> Your application has errors. Waiting for file change.
Terminate batch job (Y/N)? y

meteor-admin-lte > meteor remove yogiben:admin

Changes to your project's package version selections:

aldeed:tabular             removed from your project
aldeed:template-extension  removed from your project
meteorhacks:meteorx        removed from your project
meteorhacks:unblock        removed from your project
mfactory:admin-lte         removed from your project
raix:handlebar-helpers     removed from your project
twbs:bootstrap             removed from your project
yogiben:admin              removed from your project
zimme:active-route         removed from your project

yogiben:admin: removed dependency

meteor-admin-lte > meteor reset
Project reset.

meteor-admin-lte > meteor update less
The specified packages are at their latest compatible versions.

meteor-admin-lte > meteor add yogiben:admin

Changes to your project's package version selections:

aldeed:tabular             added, version 1.4.2
aldeed:template-extension  added, version 4.0.0
meteorhacks:meteorx        added, version 1.4.1
meteorhacks:unblock        added, version 1.1.0
mfactory:admin-lte         added, version 0.0.2
raix:handlebar-helpers     added, version 0.2.5
twbs:bootstrap             added, version 3.3.6
yogiben:admin              added, version 1.2.8
zimme:active-route         added, version 2.3.2

yogiben:admin: A complete admin dashboard solution

meteor-admin-lte > meteor
[[[[[ meteor-admin-lte ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building for web.browser:
   error: no plugin found for lib/client/css/admin-custom.less in yogiben:admin; a plugin for *.less was active when it was published but none is now

=> Your application has errors. Waiting for file change.
Terminate batch job (Y/N)? y

meteor-admin-lte > meteor --version && node -v && npm -v
Meteor 1.4.0.1
v4.4.7
3.10.5

meteor-admin-lte >

**Comment by IcyEagle** [comment]
+1

**Comment by IcyEagle** [comment]
`meteor update less` didn't update version up to 2.7.5 for some reason.

Check your _less_ version number manually in .meteor/versions.
It've helped me!

**Comment by LeonidShamis** [comment]
Yes, meteor didn't update less to the latest version.

I've removed less again and re-installed with specific version - it worked this way and the issue has been resolved:

```
meteor-admin-lte>meteor remove less
less: removed dependency
meteor-admin-lte>meteor add less@2.7.5
less: Leaner CSS language
meteor-admin-lte>meteor
```

FYI - my configuration:

```
meteor-admin-lte>meteor --version && node -v && npm -v
Meteor 1.4.1
v4.5.0
3.10.6
```

Thank you.

**Comment by brascene** [comment]
Hi Leonid,

From which directory should I run remove and add less commands?
Thanks!

**Comment by jc2** [comment]
@brascene use those commands in your meteor project (where you use "meteor" to run the project)

**Comment by brascene** [comment]
@jc2 Thank you! Thing was that I don't need to "meteor remove less", just "meteor add less@2.7.5" and it's all set up.

**Comment by tsrandrei** [comment]
Fresh meteor install based on :
Meteor 1.4.2.3
v6.9.2
3.10.9

After update of Less ( with fresh of meteor, less is 1.0 ), meteor-admin seem to work... maybe need more test. Updated documentation, I suppose is important.

**Comment by emiscience** [comment]
Just as a matter of interest, when I first came across this package, I created a **bare** app and tried to add less then. For some bizarre reason it only adds less 1.0.0 to bare versions. Despite forcing a package update..

Like this for example:

```
$ meteor create --bare fooBar
$ cd fooBar/
$ meteor list

autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.1.0  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.6.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
jquery                 1.11.10  Manipulate the DOM using CSS selectors
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.14  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.1  Dependency tracker to allow reactive callbacks

$ meteor add less
Changes to your project's package version selections:
less                       added, version 1.0.14

$ meteor update less
The specified packages are at their latest compatible versions.

```

It appears that meteor doesn't always pick up when a few of the packages are out of date as quite a few of those are old.  

You'll need to force a full update with `meteor update --all-packages`

Something else I haven't seen checked is peoples global npn caches. I still forget I have the odd module in them from time to time and spend a while frustrated at something like that.

I'm not sure if this helps, but it's saved me a lot of nightmares in the past, but `nodeenv`. You can create different virtual node environments and keep pet projects in an 'easy to dispose of' corner.

Just to show you quickly:

```
$ nodeenv ./path/to/envContainer --with-npm
 * Install prebuilt node (7.4.0) ..... done.
 * Install npm.js (latest) ... done.

$ which node
/usr/local/bin/node

$ which npm
/usr/local/bin/npm

$ echo $NODE_PATH && npm get prefix
/use/local/lib/node_modules
/usr/local/

***now for the fun***

$ . ./path/to/envContainer/bin/activate 
(envContainer)$ 

***and now***
(envContainer)$ echo $NODE_PATH && npm get prefix
/Developer/path/to/envContainer/lib/node_modules
/Developer/path/to/envContainer

```

Hope this helps someone out...

Great work by the way... Nifty!..
